### ISSUE TITLE
Rendering on iOS and macOS

### ISSUE THREAD

**Issue by ShalokShalom** [coronalabs/corona#137]
Hi there :D 

I read that you want to port your iOS and macOS implementation to Metal and it is new to me, as an engine enthusiast that anybody does so.

The community overwhelmingly decides to use [MoltenVK or MoltenGL](https://moltengl.com/), so I am interested why you chose to support so many different rendering systems as such a small studio, especially since Metal is likely to die. 

Did you know Molten and Vulkan?
Thanks a lot 🥳

**Comment by Shchvova** [comment]
Well... I don't see Metal dying any time soon. First implementation would likely be using MetalANGLE, here's first working draft  (#135). We are also working on MoltenVK implementation, but it requires major refactoring, since you know, first to move to the Vulkan. And MoltenGL is [expensive](https://moltengl.com/purchase/) proprietary product. I have no idea how to integrate it into our fee, MIT licensed engine.

**Comment by ggcrunchy** [comment]
Hi @ShalokShalom .

My Vulkan branch is here: https://github.com/ggcrunchy/corona/commits/Vulkan As of a few days ago I have several samples and a couple of my own tests working.

There are a few more common features that need handling (snaphots and friends; built-in effects and certain types of shader input; probably dynamic textures; maybe meshes), plus getting a clean shutdown / reload and dealing with scenarios like resizing.

I've been developing and testing on Windows but have definitely had MoltenVK in view.
