### ISSUE TITLE
[PLATFORM]: runtime bug

### ISSUE THREAD

**Issue by firemaplegames** [coronalabs/corona#225]
Hey there,

I believe this is a new issue, I haven't noticed this happening before.

I have the latest build, Version 2021.3637 (2021.2.3)
I am on Mac running Catalina, 10.15.7

If I now make a typo in one of my image names, say incorrectly calling it "my_image.pngg" instead of "my_image.png",
this now displays an ERROR: Runtime Error in the Console, which doesn't stop running until I fix the typo.

It should definitely cause an error, but in the past it would just display a single error in the Console, and essentially halt the Simulator.

Now it keeps running, so by the time I find and fix the typo, when I come back to the Console, there can be like 10,000 error messages.

[EDIT] This could be Timer related? I just made a empty project with a call to a missing image, and it simply displayed a warning that the image could not be found. So it must be deeper in my code where it is loading in images with a Timer. I'll keep digging.

This certainly could be something on my end, but I don't think there have been any changes in my setup. 

Let me know if this doesn't make sense or if you need clarification.
Joe

**Comment by XeduR** [comment]
Well, there's no code to look at, but this is probably the same as this: https://github.com/coronalabs/framework-timer/issues/6.

I've written a fix for this and one other issue and I'll be pushing making a PR for @Shchvova to review either late tonight or tomorrow noon, depending on what time I get home today.

**Comment by lifestreamer** [comment]
Hi,
how is this fix progressing?

I also found out problem with that bug in versions after fixing pausing timers in their callbacks.
Timer doesn't get removed from the list because callback crashes whole loop so it just repeats every enterFrame and loops infinitely.

Before that bug you just got one runtime error and app continued to work but now the app just stops working.

Can we please get this fix in the next build of corona? We have apps to update but currently can't use any of the corona builds after 14.8.2019 because of this or the pause bug in timers.
Thank you.

**Comment by Shchvova** [comment]
We are actively working on this issue.
