### ISSUE TITLE
Add luaJIT to Solar2D

### ISSUE THREAD

**Issue by DerpChest** [coronalabs/corona#255]
It would make lua so much faster.

**Comment by Shchvova** [comment]
There are a few challenges towards integrating LuaJIT.
1) Solar2D uses custom allocator. LuaJit doesn't support them. This is could have a workaround since Solar2D first actually use custom allocator as allocator, but mostly to store runtime pointer. 
2) plugins won't be compatible since LuaJIT uses its own bytecode. This has workarounds too though.
3) we customized Lua quite a bit, those patches should be ported.
4) it is hard to say how noticeable performance boost will be. Solar2D is primarily mobile game engine. So JIT won't work on iOS/tvOS because of platform restrictions. And last time I checked arm64 jit support wasnt much good. But that was a long time ago.
