### ISSUE TITLE
Bug color button

### ISSUE THREAD

**Issue by SayHelloRoman** [coronalabs/corona#268]
I was writing tic-tac-toe and accidentally noticed a bug when changing the button color. In the documentation, I did not find anything about changing the color of the button and went to Google. Here is a [video](https://youtu.be/a-6fbLXuUAE) of the errors.
I don't know what the error is about, that's why I'm writing issues

**Comment by XeduR** [comment]
This doesn't seem like a bug per se, but a programming error.

You should post your code to the [Solar2D Forums](https://forums.solar2d.com/) and ask for help there.

**Comment by SayHelloRoman** [comment]
The video shows the code where the color changes and when the color changes, the button text also changes, that is, it cannot be such that the color changes, there is no button in the text

**Comment by SayHelloRoman** [comment]
sorry for my english, this is all google translate

**Comment by XeduR** [comment]
GitHub isn't really the place for this kind of support. Again, I refer you to visit the Solar2D forums. These GitHub issues are for if you've found bugs in Solar2D itself.

---

Firstly, you are accessing private properties within the widget framework, which isn't encouraged unless you are absolutely certain of what you are doing.

Secondly, you are using globals, so you may be overwriting things as you go.

This kind of support is provided in the forums or in Solar2D Discord.

**Comment by Shchvova** [comment]
Hello! It is best to use [Forums](https://forums.solar2d.com/) for such issues. Buttons do not support color change. It is best to create a new button instead of changing colors of existing ones. But again, try sharing your code on the [forums](https://forums.solar2d.com/), you would get help there.
Here you can join our Discord chat if you want: https://discord.gg/WMtCemc
