### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [coronalabs/corona#37]
I would like to point out that an identifier like “[`_Rtt_Runtime_H__`](https://github.com/coronalabs/corona/blob/ccad6fd867f1745589e5b1a8e6fb3cf28a7e1a09/librtt/Rtt_Runtime.h#L26 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Shchvova** [comment]
Sure.

Currently I'm occupied with different projects, like migrating build system to offline. Feel free to submit such Quality of Life pull request if you want too. I'm not too concerned. We also don't really follow SEI CERT C++ Coding Standard, but if you wish to test and submit pull request with such changes, I'll accept it. Also, I would ask you to postpone it, since I have staged a lot changes to all the files, changing headers with license in it.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
