### ISSUE TITLE
Dead code in isVertexArrayObjectSupported()?

### ISSUE THREAD

**Issue by ggcrunchy** [coronalabs/corona#5]
Hi. I'm not able to test this conveniently at the moment, else I'd favor the PR route.

In the EGL version of the above-mentioned function, the test [is backward](https://github.com/coronalabs/corona/blob/master/librtt/Renderer/Rtt_GLGeometry.cpp#L71) and so support will always be reported absent, rightly or wrongly.

**Comment by Shchvova** [comment]
When we tried to use vertex array objects we faced lots of crashes in unexpected places. Like some drivers have better or worse support of it, even if they reported that support was there. We just disabled it in bunch of places, sometimes not in most elegant way  💩 

If you would to re-enable it, please make sure to severely test it on applicable platforms. And accepting such PR would take quite a time because we would have to do lots of testing as well.

Also, int long-medium there is a plan to migrate to Vulcan/MoltenVK, so this code probably would get thrown out or reworked in major way.

**Comment by Shchvova** [comment]
I think I'll close this issue. You can still comment or refer it in PRs if you like. Thank you for trying to make sense in our renderer! Really appreciating it.
