### ISSUE TITLE
Runtime Error in LFS when build for android

### ISSUE THREAD

**Issue by koyan** [coronalabs/corona#52]
While it works fine in the simulator, when build for android, the code returns a runtime error: 

The (simplified so that it has only the error) project is at: https://github.com/koyan/dirtest
Steps to reproduce: 
1) Open the project in the simulator
You should see the contents of the directory `cards` appear in the simulator screen
2) Build for Android
3) Install and run
4) The the runtime error

Folder structure
```
cards/file1.lua
cards/file2.lua
main.lua
```

main.lua:
```
local lfs = require( "lfs" )
local doc_path = system.pathForFile( "cards" )

textY = 100

for file in lfs.dir( doc_path ) do
    -- "file" is the current file or directory name
    local filenameText = display.newText( file, display.contentCenterX, textY, native.systemFont, 40 )
    filenameText:setFillColor( 1, 1, 1 )
    textY = textY + 50
    print ("The file is: " .. file)
end
```

In the simulator it lists the files in the folder as expected, showing them on the screen.
When build, installed and run on android, it gives the following error: 

```
Runtime Error

/full/path/for/the/folder/in/my/computer/dirtest/main.lua:8 bad argument for #1 to 'dir' (string expected, got nil)
```

Corona Simulator reports: Version 2020.3582 (2020.4.19)
Build with a macOs Catalina

I haven't tested on other platforms

**Comment by koyan** [comment]
Update: It works fine if you build it with "Live Builds", but it does not work without it.

**Comment by Shchvova** [comment]
Hello. You wrote an excellent report, but I have disappoint you.
Lua files are not shipped in built apps. Lua is getting compiled and compressed into the archive. If you unpack your APK you'll find that it does not contain any `.lua` files. They would be all in `.car` file in assets.
So whey you trying to `dir` for them, there is nothing to list.

Live builds work differently. They make actual copy of your source tree on the device, so files can be synced individually.

What you can do, is to rename your files to something else. We had to remove restricitons on lua's `[dofile()](https://pgl.yoyo.org/luai/i/dofile)`. This can be tricky as well, because of another android peculiarity. Android apps are shipped as APKs, archives, which don't have raw files or directories. Corona extracts files when they are requested, so you can read them, but I am not sure what about directories.

**Comment by Shchvova** [comment]
Ultimate fool proof solution would be to have a list of files you want to read and read them. You can even generate it in simulator, with only trick, not to overwrite file if nothing is changed, otherwise simulator would just keep refreshing.

**Comment by Shchvova** [comment]
But honestly. You get 10 out of 10 for this bug report.

**Comment by koyan** [comment]
Thanks. The original idea was that whenever I wanted to include a new subclass, I would only have to add the file in the correct directory, and let lua autoload them all. 
I now made it work by listing a table with the subclasses I wanted to include and just ittirating them, and now it works fine. 
Thanks for the explanation
