### ISSUE TITLE
Can't build for iOS or tvOS with with Xcode SDK 16.4

### ISSUE THREAD

**Issue by yousaf-shah** [coronalabs/corona#547]
Apple/Xcode has updated to SDK 16.4 - the latest tvOS supported is 16.1, iOS is 16.2 in Solar2D
2023.3688 (2023.3.29)

Getting the following in the SDK pulldown
16.1 (UNSUPPORTED Local tvOS SDK is 16.4 which does not match)
16.2 (UNSUPPORTED Local iOS SDK is 16.4 which does not match)

**Platforms involved**
Building on: macOS Ventura
Building for: tvOS/iOS

**Comment by Shchvova** [comment]
Hello! Thanks for the report. Fix is already in the code, but failed building several times because GitHub did not update build servers with Xcode 14.2 (still 14.1) when I tried to build. It updated yesterday and I am attempting to build again

**Comment by Shchvova** [comment]
Ah. 🤦‍♀️
We actually need Xcode Version 14.3, which is not deployed yet. 14.2 is latest available, so I can't support the latest SDK Yet.
Please download Xcode 14.2 (convenient links -https://xcodereleases.com/), rename it to `Xcode_v14_2`, move to `/Applications/, then run `sudo xcode-select -s /Applications/Xcode_v14_2.app`. This will allow you to build with previous Xcode.

Sorry for inconvenience. It could be a long wait, since Xcode 14.3 requires iOS 13, which GitHub actions does not support yet.

**Comment by yousaf-shah** [comment]
Thanks Vlad, I understand the problem - painful!
I've got both versions in my apps folder now and can build just fine after switching to the 14.2 SDK - build was accepted by the app store too so all OK.
Will stick to that method until everything is updated ...

**Comment by scottrules44** [comment]
Fixed in Solar2D 2023.3689
