### ISSUE TITLE
Transition.cancel(whatToCancel) | Not working as intended.

### ISSUE THREAD

**Issue by GitELopez** [coronalabs/corona#55]
If 'whatToCancel' is a reference to an object and it becomes nil right before calling transition.cancel(whatToCancel) then this call cancels every active transition.

Assuming a reference was passed to the function, nil or not, it was meant to cancel that transition only.

A fix suggestion would be to first check if a reference passed is nil and end execution there and change:

 ```
elseif nil == whatToCancel then
	cancelType = "all"
	cancelTarget = nil
end
```

to:
```
else
	cancelType = "all"
	cancelTarget = nil
end
```

This would still cancel all current transitions if called without passing a reference, cancel the intended transition if it's not nil, and do nothing if the reference is already nil.

**Comment by sekodev** [comment]
Have you tried this solution by importing and editing the [transition.lua](https://github.com/coronalabs/framework-transition/blob/7d1cc06b4f3bbfe35bc6eeb9cd5712ce5f4930aa/transition.lua) file to your project? I changed the part you suggested in lib.cancel() and it works the same for me. Here is the example code.

```
local trans2 = require "trans2" -- transition.lua renamed

local obj = display.newRect( 0, 0, 100, 100 )
local obj2 = display.newRect( display.contentWidth, display.contentHeight, 100, 100 )

trans2.to( obj, {time = 5000, x = display.contentCenterX, y = display.contentCenterY} )
trans2.to( obj2, {time = 5000, x = display.contentCenterX, y = display.contentCenterY} )

display.remove( obj )
obj = nil

timer.performWithDelay( 1000, function ()
		trans2.cancel( obj )
	end, 1 )
```


By the way, I guess this is intended behavior since cancel() is checking for both table and string types before getting into that nil state. I'm assuming that it's done to avoid silent error cases where the developer shouldn't be sending destroyed/non-existent objects to a transition. Also, I'm not sure if there's an easy way to understand if the sent parameter is nil by itself or destroyed.

**Comment by GitELopez** [comment]
A better solution has been provided by Xedur: [https://github.com/coronalabs/framework-transition/pull/1](url)
