### ISSUE TITLE
Error in logic in NetworkSupport.cpp —> NetworkRequestParameters

### ISSUE THREAD

**Issue by elpida-v** [coronalabs/corona#571]
I think there is an error in logic in `NetworkSupport.cpp —> NetworkRequestParameters::NetworkRequestParameters`

It appears that the `arg` variable is not always being incremented after a validation check resulting in unexpected behavior.

For example, in **line 591** when validating the 2nd argument (the “GET”/“POST”), `arg` is only incremented if the argument is a string. Otherwise, the constructor sets `fMethod` to "GET" but does not increment `arg`.

As a result, in **line 610** when validating the next element (the network listener, which is normally at index 3) the `arg` is still 2, so the check `if ( CoronaLuaIsListener( luaState, arg, "networkRequest" ) )` fails, and again the `arg` is not being incremented. 

Later, in **line 625** when the params table is checked, the code assumes that the `arg` variable is currently pointing to the fourth argument, but it still points to the second.

As I see it, when validating the various elements, the code should either increment the `arg` variable, so the rest of the code continues as expected, or set `isInvalid` to true to skip the remaining code.

**Comment by scottrules44** [comment]
I disagree that it should increment largely due to the fact the 2nd argument is required and is clearly stated in the docs. If I had a time machine I would go back and throw an invalid syntax/signature error

but given the fact this API is so old and the fact this suggestion would technically break setups that were using 

`network.request( "https://encrypted.google.com/", nil , networkListener ) -- this would break on an old project`

I don't think this will fly :(
