### ISSUE TITLE
CoronaBuilder on 3684+ and Xcode 14.3 generates an error when uploading a build to the Apple App Store

### ISSUE THREAD

**Issue by pijappi** [coronalabs/corona#577]
CoronaBuilder on 3684+ and Xcode 14.3 results in the below error message when submitting to the Apple App Store
CoronaBuilder works fine with 3683 and Xcode 14.1. 
Getting this: 

`Invalid Signature. A sealed resource is missing or invalid. The file at path “XXX.app/XXX” is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose “Clean All” in Xcode, delete the “build” directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing.`

**Comment by yousaf-shah** [comment]
I had this today when I tried to build my previously Android only project for iOS - I believe this is not a bug.
Searching the forums it seems this is due to random non-project text files sitting in the main project folder.
In my case it was a readme.md file I had added for github, I added this to my excluded files in build.settings and it built immediately after ... try it!

```
excludeFiles =
{
  -- Exclude all Android icon files, .ogg files, git files and readme.md
  ipad = { "main.sublime-workspace", "Icon.png", "Icon-*dpi.png", "*.ogg", ".git*", "*.md" },

},
```
